language: node_js
node_js: 12
stages:
- Build
- Deployment
jobs:
  include:
  - name: build
    stage: Build
    install: npm i
    script: npm run build
deploy:
  provider: heroku
  app: hidden-fjord-88704
  api_key:
    secure: R1ofRpgErhz/zotTGQH1YPOI0jYoJgAUsBS4Xt0CpdnLS8BYCUY95yLGQWj7LWZUjX1hqgjWmppOhbhYqsLEMoO6BK+wWCVa70vE4I5Uh/Zd5xG/yrTY8Zwb5atq9fdlTDcwL9O1GhYN7bQ0axK2g/BKfH9hMGX30Gy4S7WXsRpB7a0su41LKhkY+qqgjPSpLh7ZFHxnVbB3Ark+c3mNX3YVxpXbLoY2IzhAgqpdaBYluT29ew7qq2qxrJeBvSw5wTvbr6qjHe9tfk7be16qYeikXxf7pggT9/EutmW9D0ULrIFRx8ch/F5ahcGNLPzlhM40Ris3OBAS1Ez7JU6/1dlt6k276VVQUbjxVs5ugP2hEf7yvceoNI7qSu8v0KzRkRScxzdYpP/wzMsra+3vzSRuX2/Gp92wnSGxGa4k1RZ2eTPLlHyn3o1Zg+kwBSncYgaTq3pH3xjlQCRzXPwERpSUlaACkuBgFMWF3SqUR1/cRAerjMi+ukDD5z3K5ycTq0JVR2yEnKxsxFHneaoPoF5/CbWTqOL1DaT+urWDuPYp/wKJykqi3+9MfQuoArI5XSgQeehNPEocmHx1q/xGs3Asy2/7VixXrxSzW4DkZA3cwEb7ODLD+Z1eapoMzRL/DhMsSLncJSLYsrnfMAI/p1jVGlQQNz5ji1x7nXLpLw0=
    on:
    all_branches: true
notifications:
  slack: flint-academy:Lw4aUwGziDIUuVOEhVjqw89B
env:
  global:
    secure: c+w+q9DJOWyOGs2A2Ks89ZxworvQ7UAVYp1hg+3IlMQGqytP4Swwpr/9gOqHTXvfSnHmcBVoVre5J95VhVlGfSpgbEVDuYdxJXITaIENRKfztapnV4rOfvLnEW4grECzWLkS3AT9R6ykXtu+V9EMP+gGwG46gDrHhgJJ1x9g6f0b6+eignTuvCbyenaqQNwpABoL1HxSUq1ChcKGs29aNkseSMar+K1Wii13BSSWQLBgoCA9hu2zXTKaioXgk1JeKxXzhS3eUg1551D7yHYvM48cse+3dNL2U26eY77FgJGa9n1B/8ii/qSyHqEzS+5XJpBRrD8pzF0dy2g/MFQ7/mZUa//4UEZ4Ehbjr3rIdmIEaCLSUiubIzYQ4NScpAaLhVw9j7DWGOoNZEqNP73Mkl+7y+emsjzA5M8s1vfl45LiaLHBelMH6HANERzXDWb9rl7SoOzKE4LW4ipLSHWWre7/JKT3e50Su6bVPY6KkHUH0lOl7m86kQzIVLaiNWKyPBhbr7b9752N0Uo7dSzKIVUGvb9lRRNWd90ZsZMk39PEcc0Hui61uK0E8eXTDIe1Ij+RILIjQlSbbGKwuImMgTIniHmQ2aXkJAkzFSUNuENVViiFvNPR2LBHH4IOaiExYZm6G2Gqjxa/78nWTFh7ww3lsaA/bpjwdKaAKGVGtHU=
