language: node_js
node_js: 12
stages:
- Build
- Deployment
jobs:
  include:
  - name: build
    stage: Build
    install: npm i
    script: npm run build
deploy:
  provider: heroku
  app: hidden-fjord-88704
  api_key:
    secure: RSL2RJAz3BrvmMRY4dHF3ZkWbZqtrUmIfobtsj8e5dYerUv3+myR9BZNKyZpVVB+joontkhvupywULx6HWii1OE2GacmkGTnjPTehQcYemm6QWnAwM7t3Kb25a7X4APa+AStl8Q9qdAVhABEu3edjtjLkrBKAjk/y7xJKeuEA62zxIAT0MJyprFzUpn4oiPGh0h7ncwADNF6XDZPJGy3bPz2aL060RfxUzIciUhFyN5FbywMW3g8nJE2DJsXUIbBoIrOPqGySMmycYVu16VjjtFek7Lsix6Y+ljHLP534Q+TkYFOlcA8fk9xluU5W3Z7Zn7i9bcPZ1NQ/XFeLF9wyBaOVozoeS9vVmOTOcpfjkMhVtIFBz99DCiLVQC9TrM4UxNy8pB5KMtLQberXNl1auJBL3CvqWy1IO5RoS1Pbo/tzhFbq9NwN2b7CUwcX/xaytf7w6BQ/P9gvtMZgUOW/DisqQv1fgLNTN+iXpMurYiyjw8J8aqg4lcfS1vCeMlw0wnEsCFacGU0NKWjJu9gcn4X5ON2k5wQaKQ7Ro9a1aOSvKJEP3CB3d8NDrYUuCiR6VhjugwUOI5y/+1sGc/2zBgg+7HOCXsPR+TqkeYjBs0jr8Izw0RY7qXaymGONSkBeY7jFyr7Mt/RukDDmvKRbwInIsf/cVEojZzL683DMa4=
notifications:
  slack: flint-academy:Lw4aUwGziDIUuVOEhVjqw89B
