language: node_js
node_js: 12
stages:
- Build
- Deployment
jobs:
  include:
  - name: build
    stage: Build
    install: npm i
    script: npm run build
deploy:
  provider: heroku
  app: hidden-fjord-88704
  api_key:
    secure: R1ofRpgErhz/zotTGQH1YPOI0jYoJgAUsBS4Xt0CpdnLS8BYCUY95yLGQWj7LWZUjX1hqgjWmppOhbhYqsLEMoO6BK+wWCVa70vE4I5Uh/Zd5xG/yrTY8Zwb5atq9fdlTDcwL9O1GhYN7bQ0axK2g/BKfH9hMGX30Gy4S7WXsRpB7a0su41LKhkY+qqgjPSpLh7ZFHxnVbB3Ark+c3mNX3YVxpXbLoY2IzhAgqpdaBYluT29ew7qq2qxrJeBvSw5wTvbr6qjHe9tfk7be16qYeikXxf7pggT9/EutmW9D0ULrIFRx8ch/F5ahcGNLPzlhM40Ris3OBAS1Ez7JU6/1dlt6k276VVQUbjxVs5ugP2hEf7yvceoNI7qSu8v0KzRkRScxzdYpP/wzMsra+3vzSRuX2/Gp92wnSGxGa4k1RZ2eTPLlHyn3o1Zg+kwBSncYgaTq3pH3xjlQCRzXPwERpSUlaACkuBgFMWF3SqUR1/cRAerjMi+ukDD5z3K5ycTq0JVR2yEnKxsxFHneaoPoF5/CbWTqOL1DaT+urWDuPYp/wKJykqi3+9MfQuoArI5XSgQeehNPEocmHx1q/xGs3Asy2/7VixXrxSzW4DkZA3cwEb7ODLD+Z1eapoMzRL/DhMsSLncJSLYsrnfMAI/p1jVGlQQNz5ji1x7nXLpLw0=
    on:
    all_branches: true

notifications:
  slack: flint-academy:Lw4aUwGziDIUuVOEhVjqw89B
